name: Bug Report
description: Report a bug or issue with WebLinq
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of WebLinq is affected?
      options:
        - Backend API
        - Frontend Dashboard
        - Documentation
        - MCP Server
        - Browser Session Management
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: 'OS, Node.js version, browser (if applicable)'
      placeholder: 'macOS 14.0, Node.js 18.17.0, Chrome 119'
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the problem
      placeholder: Any additional information...
